#bankdef ROM {
  #addr 0x0000
  #addr_end 0x8000 ;end is exclusive
  #outp 0
  #bits 8 ;8-Bit CPU
  #fill
}

#bankdef RAM {
  #addr 0x8000  ;e.g. for store: assert that addr is a valid RAM address 
  #addr_end 0x10000 ;end is exclusive
  #bits 8 ;8-Bit CPU
}

#subruledef register { ;subruledef prevents the mnemonics from being used as freestanding instructions
  A    => 0b000
  TMP  => 0b001
  B    => 0b010
  C    => 0b011
  X    => 0b100
  Y    => 0b101
}

#subruledef idxregister { ;subruledef prevents the mnemonics from being used as freestanding instructions
  X    => 0b0
  Y    => 0b1
}

#subruledef lcdregister { ;subruledef prevents the mnemonics from being used as freestanding instructions
  CTRL => 0b0
  DATA => 0b1
}

#ruledef {
	add                                                      => 0b11010000
	addi {imm: i8}                                           => asm{ li TMP, {imm} } @ asm{ add }
	addc                                                     => 0b00100100
	addci {imm: i8}                                          => asm{ li TMP, {imm} } @ asm{ addc }
	sub                                                      => 0b11010010
	subc                                                     => 0b00100101
	subci {imm: i8}                                          => asm{ li TMP, {imm} } @ asm{ subc }
	and                                                      => 0b11100010
	andi {imm: i8}                                           => asm{ li TMP, {imm} } @ asm{ and }
	or                                                       => 0b11100011
	ori {imm: i8}                                            => asm{ li TMP, {imm} } @ asm{ or }
	xor                                                      => 0b11110011
	xori {imm: i8}                                           => asm{ li TMP, {imm} } @ asm{ xor }
	not                                                      => 0b11100100
	neg                                                      => asm{ not } @ asm{ addi 1 }
	shl                                                      => 0b11110010
	slr                                                      => 0b11010001
	sar                                                      => 0b11110000
	ror                                                      => 0b11110100
	rol                                                      => 0b11110001
	clr {reg: register}                                      => asm{ li {reg}, 0 }
	mov BUF, A                                               => 0b10101111
	mov TMP, BUF                                             => 0b10111111
	mov A, F                                                 => 0b10011110
	mov TMP, F                                               => 0b10101110
	mov B, F                                                 => 0b10111110
	mov C, F                                                 => 0b11001110
	mov X, F                                                 => 0b11011110
	mov Y, F                                                 => 0b11101110
	mov {regd: register}, {regs: register}                   =>
			{
				regd == regs ? 0b00000000`8 : ; emit a nop so this instruction also becomes 4 bytes long and the assembler can choose the more specific rule with less bytes
				regd == 0b000 ? (
					regs == 0b010 ? 0b10111000`8 :
					regs == 0b011 ? 0b11001000`8 :
					regs == 0b001 ? 0b10101000`8 :
					regs == 0b100 ? 0b11011000`8 :
					regs == 0b101 ? 0b10011101`8 :
					assert(false, "Invalid mov combination found!")
				) :
				regd == 0b010 ? (
					regs == 0b000 ? 0b10011001`8 :
					regs == 0b011 ? 0b11001010`8 :
					regs == 0b001 ? 0b10101001`8 :
					regs == 0b100 ? 0b11011010`8 :
					regs == 0b101 ? 0b10111101`8 :
					assert(false, "Invalid mov combination found!")
				) :
				regd == 0b011 ? (
					regs == 0b000 ? 0b10011010`8 :
					regs == 0b010 ? 0b10111010`8 :
					regs == 0b001 ? 0b10101010`8 :
					regs == 0b100 ? 0b11011011`8 :
					regs == 0b101 ? 0b11001101`8 :
					assert(false, "Invalid mov combination found!")
				) :
				regd == 0b001 ? (
					regs == 0b000 ? 0b10011000`8 :
					regs == 0b010 ? 0b10111001`8 :
					regs == 0b011 ? 0b11001001`8 :
					regs == 0b100 ? 0b11011001`8 :
					regs == 0b101 ? 0b10101101`8 :
					assert(false, "Invalid mov combination found!")
				) :
				regd == 0b100 ? (
					regs == 0b000 ? 0b10011011`8 :
					regs == 0b010 ? 0b10111011`8 :
					regs == 0b011 ? 0b11001011`8 :
					regs == 0b001 ? 0b10101011`8 :
					regs == 0b101 ? 0b11011101`8 :
					assert(false, "Invalid mov combination found!")
				) :
				regd == 0b101 ? (
					regs == 0b000 ? 0b10011100`8 :
					regs == 0b010 ? 0b10111100`8 :
					regs == 0b011 ? 0b11001100`8 :
					regs == 0b001 ? 0b10101100`8 :
					regs == 0b100 ? 0b11011100`8 :
					assert(false, "Invalid mov combination found!")
				) :
				assert(false, "Invalid mov combination found!")
			}
	ld {reg: register}, {addr: u16}                          => 0b00010 @ reg @ le(addr)
	ldo {reg: register}, {idxreg: idxregister}, {addr: u16}  => 0b0011 @ reg @ idxreg @ le(addr)
	ldsprel {reg: register}, {imm: i8}                       => 0b01010 @ reg @ imm
	st {reg: register}, {addr: u16}                          => 0b00011 @ reg @ le(addr)
	sto {reg: register}, {idxreg: idxregister}, {addr: u16}  => 0b0100 @ reg @ idxreg @ le(addr)
	stsprel {reg: register}, {addr: u16}                     => 0b01011 @ reg @ le(addr)
	li {reg: register}, {imm: i8}                            => 0b01101 @ reg @ imm
	push {reg: register}                                     => 0b10010 @ reg
	pop {reg: register}                                      => 0b10100 @ reg
	peek {reg: register}                                     => 0b10110 @ reg
	incx                                                     => 0b01100100
	incy                                                     => 0b01100110
	incm {addr: u16}                                         => asm{ ld X, {addr} } @ asm{ incx } @ asm{ st X, {addr} }
	decx                                                     => 0b01100101
	decy                                                     => 0b01100111
	decm {addr: u16}                                         => asm{ ld X, {addr} } @ asm{ decx } @ asm{ st X, {addr} }
	out7sd {reg: register}                                   => 0b00101 @ reg
	s7sdsm                                                   => 0b11000010
	s7sdum                                                   => 0b00000011
	out7sdi {imm: i8}                                        => 0b00101111 @ imm
	outlcd {lcdreg: lcdregister}, {reg: register}            => 0b1000 @ lcdreg @ reg
	outlcdi {lcdreg: lcdregister}, {imm: i8}                 => 0b1000111 @ lcdreg @ imm
	lcdrda {lcdreg: lcdregister}                             => 0b1000110 @ lcdreg
	rxrd {reg: register}                                     => 0b01110 @ reg
	txsend {reg: register}                                   => 0b01111 @ reg
	txsendi {imm: i8}                                        => 0b01111111 @ imm
	nop                                                      => 0b00000000
	hlt                                                      => 0b00000001
	call {addr: u16}                                         => asm{ 
			li TMP, nextInstructionAddress[15:8]
			push TMP
			li TMP, nextInstructionAddress[7:0]
			push TMP
			jmp {addr}
			nextInstructionAddress: }
	ret                                                      => 0b00000111
	jmp {addr: u16}                                          => 0b00000101 @ le(addr)
	jmpr                                                     => 0b00000110
	jmpind {addr: u16}                                       => 0b00100110 @ le(addr)
	beq {addr: u16}                                          => 0b00001010 @ le(addr)
	beqi {imm: i8}, {addr: u16}                              => asm{ li TMP, {imm} } @ asm{ beq {addr} }
	bne {addr: u16}                                          => 0b00001011 @ le(addr)
	bnei {imm: i8}, {addr: u16}                              => asm{ li TMP, {imm} } @ asm{ bne {addr} }
	blt {addr: u16}                                          => 0b10010110 @ le(addr)
	blti {imm: i8}, {addr: u16}                              => asm{ li TMP, {imm} } @ asm{ blt {addr} }
	bltu {addr: u16}                                         => 0b00100010 @ le(addr)
	bltiu {imm: i8}, {addr: u16}                             => asm{ li TMP, {imm} } @ asm{ bltu {addr} }
	ble {addr: u16}                                          => 0b10100110 @ le(addr)
	blei {imm: i8}, {addr: u16}                              => asm{ li TMP, {imm} } @ asm{ ble {addr} }
	bleu {addr: u16}                                         => 0b11000000 @ le(addr)
	bleiu {imm: i8}, {addr: u16}                             => asm{ li TMP, {imm} } @ asm{ bleu {addr} }
	bge {addr: u16}                                          => 0b10010111 @ le(addr)
	bgei {imm: i8}, {addr: u16}                              => asm{ li TMP, {imm} } @ asm{ bge {addr} }
	bgeu {addr: u16}                                         => 0b00100011 @ le(addr)
	bgeiu {imm: i8}, {addr: u16}                             => asm{ li TMP, {imm} } @ asm{ bgeu {addr} }
	bgt {addr: u16}                                          => 0b10100111 @ le(addr)
	bgti {imm: i8}, {addr: u16}                              => asm{ li TMP, {imm} } @ asm{ bgt {addr} }
	bgtu {addr: u16}                                         => 0b11000001 @ le(addr)
	bgtiu {imm: i8}, {addr: u16}                             => asm{ li TMP, {imm} } @ asm{ bgtu {addr} }
	bzs {addr: u16}                                          => 0b00001000 @ le(addr)
	bzc {addr: u16}                                          => 0b00001001 @ le(addr)
	bcs {addr: u16}                                          => 0b00100000 @ le(addr)
	bcc {addr: u16}                                          => 0b00100001 @ le(addr)
	bns {addr: u16}                                          => 0b11110101 @ le(addr)
	bnc {addr: u16}                                          => 0b11110110 @ le(addr)
	bvs {addr: u16}                                          => 0b01100000 @ le(addr)
	bvc {addr: u16}                                          => 0b01100001 @ le(addr)
	brxrdys {addr: u16}                                      => 0b11100000 @ le(addr)
	brxrdyc {addr: u16}                                      => 0b11100001 @ le(addr)
	btxrdys {addr: u16}                                      => 0b11101000 @ le(addr)
	btxrdyc {addr: u16}                                      => 0b11101001 @ le(addr)
			




  ; Syntactic Sugar Rules:
	ld {reg: register}, {idxreg: idxregister}[{addr: u16}]   => asm{ ldo {reg}, {idxreg}, {addr}  } 
	st {reg: register}, {idxreg: idxregister}[{addr: u16}]   => asm{ sto {reg}, {idxreg}, {addr}  } 
	ld {reg: register}, {imm: i8}[SP]                        => asm{ ldsprel {reg}, {imm} } 
	st {reg: register}, {imm: i8}[SP]                        => asm{ stsprel {reg}, {imm} } 
	jmp [A, TMP]                                             => asm{ jmpr } 
	jmp ({addr: u16})                                        => asm{ jmpind {addr} }
	add {reg1: register}, {reg2: register}, {reg3: register} => asm{ mov A, {reg2} } @ asm{ mov TMP, {reg3} } @ asm{ add } @ asm{ mov {reg1}, A }
	add A, A, A                                              => asm{ mov TMP, A } @ asm{ add }
	add A, A, TMP                                            => asm{ add }
	add A, A, B                                              => asm{ mov TMP, B } @ asm{ add }
	add A, A, C                                              => asm{ mov TMP, C } @ asm{ add }
	add A, A, X                                              => asm{ mov TMP, X } @ asm{ add }
	add A, A, Y                                              => asm{ mov TMP, Y } @ asm{ add }
	add A, TMP, A                                            => asm{ mov A, TMP } @ asm{ mov TMP, A } @ asm{ add }
	add A, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ add }
	add A, TMP, B                                            => asm{ mov A, TMP } @ asm{ mov TMP, B } @ asm{ add }
	add A, TMP, C                                            => asm{ mov A, TMP } @ asm{ mov TMP, C } @ asm{ add }
	add A, TMP, X                                            => asm{ mov A, TMP } @ asm{ mov TMP, X } @ asm{ add }
	add A, TMP, Y                                            => asm{ mov A, TMP } @ asm{ mov TMP, Y } @ asm{ add }
	add A, B, A                                              => asm{ mov A, B } @ asm{ mov TMP, A } @ asm{ add }
	add A, B, TMP                                            => asm{ mov A, B } @ asm{ add }
	add A, B, B                                              => asm{ mov A, B } @ asm{ mov TMP, B } @ asm{ add }
	add A, B, C                                              => asm{ mov A, B } @ asm{ mov TMP, C } @ asm{ add }
	add A, B, X                                              => asm{ mov A, B } @ asm{ mov TMP, X } @ asm{ add }
	add A, B, Y                                              => asm{ mov A, B } @ asm{ mov TMP, Y } @ asm{ add }
	add A, C, A                                              => asm{ mov A, C } @ asm{ mov TMP, A } @ asm{ add }
	add A, C, TMP                                            => asm{ mov A, C } @ asm{ add }
	add A, C, B                                              => asm{ mov A, C } @ asm{ mov TMP, B } @ asm{ add }
	add A, C, C                                              => asm{ mov A, C } @ asm{ mov TMP, C } @ asm{ add }
	add A, C, X                                              => asm{ mov A, C } @ asm{ mov TMP, X } @ asm{ add }
	add A, C, Y                                              => asm{ mov A, C } @ asm{ mov TMP, Y } @ asm{ add }
	add A, X, A                                              => asm{ mov A, X } @ asm{ mov TMP, A } @ asm{ add }
	add A, X, TMP                                            => asm{ mov A, X } @ asm{ add }
	add A, X, B                                              => asm{ mov A, X } @ asm{ mov TMP, B } @ asm{ add }
	add A, X, C                                              => asm{ mov A, X } @ asm{ mov TMP, C } @ asm{ add }
	add A, X, X                                              => asm{ mov A, X } @ asm{ mov TMP, X } @ asm{ add }
	add A, X, Y                                              => asm{ mov A, X } @ asm{ mov TMP, Y } @ asm{ add }
	add A, Y, A                                              => asm{ mov A, Y } @ asm{ mov TMP, A } @ asm{ add }
	add A, Y, TMP                                            => asm{ mov A, Y } @ asm{ add }
	add A, Y, B                                              => asm{ mov A, Y } @ asm{ mov TMP, B } @ asm{ add }
	add A, Y, C                                              => asm{ mov A, Y } @ asm{ mov TMP, C } @ asm{ add }
	add A, Y, X                                              => asm{ mov A, Y } @ asm{ mov TMP, X } @ asm{ add }
	add A, Y, Y                                              => asm{ mov A, Y } @ asm{ mov TMP, Y } @ asm{ add }
	add TMP, A, A                                            => asm{ mov TMP, A } @ asm{ add } @ asm{ mov TMP, A }
	add TMP, A, TMP                                          => asm{ add } @ asm{ mov TMP, A }
	add TMP, A, B                                            => asm{ mov TMP, B } @ asm{ add } @ asm{ mov TMP, A }
	add TMP, A, C                                            => asm{ mov TMP, C } @ asm{ add } @ asm{ mov TMP, A }
	add TMP, A, X                                            => asm{ mov TMP, X } @ asm{ add } @ asm{ mov TMP, A }
	add TMP, A, Y                                            => asm{ mov TMP, Y } @ asm{ add } @ asm{ mov TMP, A }
	add TMP, TMP, TMP                                        => asm{ mov A, TMP } @ asm{ add } @ asm{ mov TMP, A }
	add TMP, B, TMP                                          => asm{ mov A, B } @ asm{ add } @ asm{ mov TMP, A }
	add TMP, C, TMP                                          => asm{ mov A, C } @ asm{ add } @ asm{ mov TMP, A }
	add TMP, X, TMP                                          => asm{ mov A, X } @ asm{ add } @ asm{ mov TMP, A }
	add TMP, Y, TMP                                          => asm{ mov A, Y } @ asm{ add } @ asm{ mov TMP, A }
	add B, A, A                                              => asm{ mov TMP, A } @ asm{ add } @ asm{ mov B, A }
	add B, A, TMP                                            => asm{ add } @ asm{ mov B, A }
	add B, A, B                                              => asm{ mov TMP, B } @ asm{ add } @ asm{ mov B, A }
	add B, A, C                                              => asm{ mov TMP, C } @ asm{ add } @ asm{ mov B, A }
	add B, A, X                                              => asm{ mov TMP, X } @ asm{ add } @ asm{ mov B, A }
	add B, A, Y                                              => asm{ mov TMP, Y } @ asm{ add } @ asm{ mov B, A }
	add B, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ add } @ asm{ mov B, A }
	add B, B, TMP                                            => asm{ mov A, B } @ asm{ add } @ asm{ mov B, A }
	add B, C, TMP                                            => asm{ mov A, C } @ asm{ add } @ asm{ mov B, A }
	add B, X, TMP                                            => asm{ mov A, X } @ asm{ add } @ asm{ mov B, A }
	add B, Y, TMP                                            => asm{ mov A, Y } @ asm{ add } @ asm{ mov B, A }
	add C, A, A                                              => asm{ mov TMP, A } @ asm{ add } @ asm{ mov C, A }
	add C, A, TMP                                            => asm{ add } @ asm{ mov C, A }
	add C, A, B                                              => asm{ mov TMP, B } @ asm{ add } @ asm{ mov C, A }
	add C, A, C                                              => asm{ mov TMP, C } @ asm{ add } @ asm{ mov C, A }
	add C, A, X                                              => asm{ mov TMP, X } @ asm{ add } @ asm{ mov C, A }
	add C, A, Y                                              => asm{ mov TMP, Y } @ asm{ add } @ asm{ mov C, A }
	add C, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ add } @ asm{ mov C, A }
	add C, B, TMP                                            => asm{ mov A, B } @ asm{ add } @ asm{ mov C, A }
	add C, C, TMP                                            => asm{ mov A, C } @ asm{ add } @ asm{ mov C, A }
	add C, X, TMP                                            => asm{ mov A, X } @ asm{ add } @ asm{ mov C, A }
	add C, Y, TMP                                            => asm{ mov A, Y } @ asm{ add } @ asm{ mov C, A }
	add X, A, A                                              => asm{ mov TMP, A } @ asm{ add } @ asm{ mov X, A }
	add X, A, TMP                                            => asm{ add } @ asm{ mov X, A }
	add X, A, B                                              => asm{ mov TMP, B } @ asm{ add } @ asm{ mov X, A }
	add X, A, C                                              => asm{ mov TMP, C } @ asm{ add } @ asm{ mov X, A }
	add X, A, X                                              => asm{ mov TMP, X } @ asm{ add } @ asm{ mov X, A }
	add X, A, Y                                              => asm{ mov TMP, Y } @ asm{ add } @ asm{ mov X, A }
	add X, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ add } @ asm{ mov X, A }
	add X, B, TMP                                            => asm{ mov A, B } @ asm{ add } @ asm{ mov X, A }
	add X, C, TMP                                            => asm{ mov A, C } @ asm{ add } @ asm{ mov X, A }
	add X, X, TMP                                            => asm{ mov A, X } @ asm{ add } @ asm{ mov X, A }
	add X, Y, TMP                                            => asm{ mov A, Y } @ asm{ add } @ asm{ mov X, A }
	add Y, A, A                                              => asm{ mov TMP, A } @ asm{ add } @ asm{ mov Y, A }
	add Y, A, TMP                                            => asm{ add } @ asm{ mov Y, A }
	add Y, A, B                                              => asm{ mov TMP, B } @ asm{ add } @ asm{ mov Y, A }
	add Y, A, C                                              => asm{ mov TMP, C } @ asm{ add } @ asm{ mov Y, A }
	add Y, A, X                                              => asm{ mov TMP, X } @ asm{ add } @ asm{ mov Y, A }
	add Y, A, Y                                              => asm{ mov TMP, Y } @ asm{ add } @ asm{ mov Y, A }
	add Y, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ add } @ asm{ mov Y, A }
	add Y, B, TMP                                            => asm{ mov A, B } @ asm{ add } @ asm{ mov Y, A }
	add Y, C, TMP                                            => asm{ mov A, C } @ asm{ add } @ asm{ mov Y, A }
	add Y, X, TMP                                            => asm{ mov A, X } @ asm{ add } @ asm{ mov Y, A }
	add Y, Y, TMP                                            => asm{ mov A, Y } @ asm{ add } @ asm{ mov Y, A }
	addc {reg1: register}, {reg2: register}, {reg3: register} => asm{ mov A, {reg2} } @ asm{ mov TMP, {reg3} } @ asm{ addc } @ asm{ mov {reg1}, A }
	addc A, A, A                                             => asm{ mov TMP, A } @ asm{ addc }
	addc A, A, TMP                                           => asm{ addc }
	addc A, A, B                                             => asm{ mov TMP, B } @ asm{ addc }
	addc A, A, C                                             => asm{ mov TMP, C } @ asm{ addc }
	addc A, A, X                                             => asm{ mov TMP, X } @ asm{ addc }
	addc A, A, Y                                             => asm{ mov TMP, Y } @ asm{ addc }
	addc A, TMP, A                                           => asm{ mov A, TMP } @ asm{ mov TMP, A } @ asm{ addc }
	addc A, TMP, TMP                                         => asm{ mov A, TMP } @ asm{ addc }
	addc A, TMP, B                                           => asm{ mov A, TMP } @ asm{ mov TMP, B } @ asm{ addc }
	addc A, TMP, C                                           => asm{ mov A, TMP } @ asm{ mov TMP, C } @ asm{ addc }
	addc A, TMP, X                                           => asm{ mov A, TMP } @ asm{ mov TMP, X } @ asm{ addc }
	addc A, TMP, Y                                           => asm{ mov A, TMP } @ asm{ mov TMP, Y } @ asm{ addc }
	addc A, B, A                                             => asm{ mov A, B } @ asm{ mov TMP, A } @ asm{ addc }
	addc A, B, TMP                                           => asm{ mov A, B } @ asm{ addc }
	addc A, B, B                                             => asm{ mov A, B } @ asm{ mov TMP, B } @ asm{ addc }
	addc A, B, C                                             => asm{ mov A, B } @ asm{ mov TMP, C } @ asm{ addc }
	addc A, B, X                                             => asm{ mov A, B } @ asm{ mov TMP, X } @ asm{ addc }
	addc A, B, Y                                             => asm{ mov A, B } @ asm{ mov TMP, Y } @ asm{ addc }
	addc A, C, A                                             => asm{ mov A, C } @ asm{ mov TMP, A } @ asm{ addc }
	addc A, C, TMP                                           => asm{ mov A, C } @ asm{ addc }
	addc A, C, B                                             => asm{ mov A, C } @ asm{ mov TMP, B } @ asm{ addc }
	addc A, C, C                                             => asm{ mov A, C } @ asm{ mov TMP, C } @ asm{ addc }
	addc A, C, X                                             => asm{ mov A, C } @ asm{ mov TMP, X } @ asm{ addc }
	addc A, C, Y                                             => asm{ mov A, C } @ asm{ mov TMP, Y } @ asm{ addc }
	addc A, X, A                                             => asm{ mov A, X } @ asm{ mov TMP, A } @ asm{ addc }
	addc A, X, TMP                                           => asm{ mov A, X } @ asm{ addc }
	addc A, X, B                                             => asm{ mov A, X } @ asm{ mov TMP, B } @ asm{ addc }
	addc A, X, C                                             => asm{ mov A, X } @ asm{ mov TMP, C } @ asm{ addc }
	addc A, X, X                                             => asm{ mov A, X } @ asm{ mov TMP, X } @ asm{ addc }
	addc A, X, Y                                             => asm{ mov A, X } @ asm{ mov TMP, Y } @ asm{ addc }
	addc A, Y, A                                             => asm{ mov A, Y } @ asm{ mov TMP, A } @ asm{ addc }
	addc A, Y, TMP                                           => asm{ mov A, Y } @ asm{ addc }
	addc A, Y, B                                             => asm{ mov A, Y } @ asm{ mov TMP, B } @ asm{ addc }
	addc A, Y, C                                             => asm{ mov A, Y } @ asm{ mov TMP, C } @ asm{ addc }
	addc A, Y, X                                             => asm{ mov A, Y } @ asm{ mov TMP, X } @ asm{ addc }
	addc A, Y, Y                                             => asm{ mov A, Y } @ asm{ mov TMP, Y } @ asm{ addc }
	addc TMP, A, A                                           => asm{ mov TMP, A } @ asm{ addc } @ asm{ mov TMP, A }
	addc TMP, A, TMP                                         => asm{ addc } @ asm{ mov TMP, A }
	addc TMP, A, B                                           => asm{ mov TMP, B } @ asm{ addc } @ asm{ mov TMP, A }
	addc TMP, A, C                                           => asm{ mov TMP, C } @ asm{ addc } @ asm{ mov TMP, A }
	addc TMP, A, X                                           => asm{ mov TMP, X } @ asm{ addc } @ asm{ mov TMP, A }
	addc TMP, A, Y                                           => asm{ mov TMP, Y } @ asm{ addc } @ asm{ mov TMP, A }
	addc TMP, TMP, TMP                                       => asm{ mov A, TMP } @ asm{ addc } @ asm{ mov TMP, A }
	addc TMP, B, TMP                                         => asm{ mov A, B } @ asm{ addc } @ asm{ mov TMP, A }
	addc TMP, C, TMP                                         => asm{ mov A, C } @ asm{ addc } @ asm{ mov TMP, A }
	addc TMP, X, TMP                                         => asm{ mov A, X } @ asm{ addc } @ asm{ mov TMP, A }
	addc TMP, Y, TMP                                         => asm{ mov A, Y } @ asm{ addc } @ asm{ mov TMP, A }
	addc B, A, A                                             => asm{ mov TMP, A } @ asm{ addc } @ asm{ mov B, A }
	addc B, A, TMP                                           => asm{ addc } @ asm{ mov B, A }
	addc B, A, B                                             => asm{ mov TMP, B } @ asm{ addc } @ asm{ mov B, A }
	addc B, A, C                                             => asm{ mov TMP, C } @ asm{ addc } @ asm{ mov B, A }
	addc B, A, X                                             => asm{ mov TMP, X } @ asm{ addc } @ asm{ mov B, A }
	addc B, A, Y                                             => asm{ mov TMP, Y } @ asm{ addc } @ asm{ mov B, A }
	addc B, TMP, TMP                                         => asm{ mov A, TMP } @ asm{ addc } @ asm{ mov B, A }
	addc B, B, TMP                                           => asm{ mov A, B } @ asm{ addc } @ asm{ mov B, A }
	addc B, C, TMP                                           => asm{ mov A, C } @ asm{ addc } @ asm{ mov B, A }
	addc B, X, TMP                                           => asm{ mov A, X } @ asm{ addc } @ asm{ mov B, A }
	addc B, Y, TMP                                           => asm{ mov A, Y } @ asm{ addc } @ asm{ mov B, A }
	addc C, A, A                                             => asm{ mov TMP, A } @ asm{ addc } @ asm{ mov C, A }
	addc C, A, TMP                                           => asm{ addc } @ asm{ mov C, A }
	addc C, A, B                                             => asm{ mov TMP, B } @ asm{ addc } @ asm{ mov C, A }
	addc C, A, C                                             => asm{ mov TMP, C } @ asm{ addc } @ asm{ mov C, A }
	addc C, A, X                                             => asm{ mov TMP, X } @ asm{ addc } @ asm{ mov C, A }
	addc C, A, Y                                             => asm{ mov TMP, Y } @ asm{ addc } @ asm{ mov C, A }
	addc C, TMP, TMP                                         => asm{ mov A, TMP } @ asm{ addc } @ asm{ mov C, A }
	addc C, B, TMP                                           => asm{ mov A, B } @ asm{ addc } @ asm{ mov C, A }
	addc C, C, TMP                                           => asm{ mov A, C } @ asm{ addc } @ asm{ mov C, A }
	addc C, X, TMP                                           => asm{ mov A, X } @ asm{ addc } @ asm{ mov C, A }
	addc C, Y, TMP                                           => asm{ mov A, Y } @ asm{ addc } @ asm{ mov C, A }
	addc X, A, A                                             => asm{ mov TMP, A } @ asm{ addc } @ asm{ mov X, A }
	addc X, A, TMP                                           => asm{ addc } @ asm{ mov X, A }
	addc X, A, B                                             => asm{ mov TMP, B } @ asm{ addc } @ asm{ mov X, A }
	addc X, A, C                                             => asm{ mov TMP, C } @ asm{ addc } @ asm{ mov X, A }
	addc X, A, X                                             => asm{ mov TMP, X } @ asm{ addc } @ asm{ mov X, A }
	addc X, A, Y                                             => asm{ mov TMP, Y } @ asm{ addc } @ asm{ mov X, A }
	addc X, TMP, TMP                                         => asm{ mov A, TMP } @ asm{ addc } @ asm{ mov X, A }
	addc X, B, TMP                                           => asm{ mov A, B } @ asm{ addc } @ asm{ mov X, A }
	addc X, C, TMP                                           => asm{ mov A, C } @ asm{ addc } @ asm{ mov X, A }
	addc X, X, TMP                                           => asm{ mov A, X } @ asm{ addc } @ asm{ mov X, A }
	addc X, Y, TMP                                           => asm{ mov A, Y } @ asm{ addc } @ asm{ mov X, A }
	addc Y, A, A                                             => asm{ mov TMP, A } @ asm{ addc } @ asm{ mov Y, A }
	addc Y, A, TMP                                           => asm{ addc } @ asm{ mov Y, A }
	addc Y, A, B                                             => asm{ mov TMP, B } @ asm{ addc } @ asm{ mov Y, A }
	addc Y, A, C                                             => asm{ mov TMP, C } @ asm{ addc } @ asm{ mov Y, A }
	addc Y, A, X                                             => asm{ mov TMP, X } @ asm{ addc } @ asm{ mov Y, A }
	addc Y, A, Y                                             => asm{ mov TMP, Y } @ asm{ addc } @ asm{ mov Y, A }
	addc Y, TMP, TMP                                         => asm{ mov A, TMP } @ asm{ addc } @ asm{ mov Y, A }
	addc Y, B, TMP                                           => asm{ mov A, B } @ asm{ addc } @ asm{ mov Y, A }
	addc Y, C, TMP                                           => asm{ mov A, C } @ asm{ addc } @ asm{ mov Y, A }
	addc Y, X, TMP                                           => asm{ mov A, X } @ asm{ addc } @ asm{ mov Y, A }
	addc Y, Y, TMP                                           => asm{ mov A, Y } @ asm{ addc } @ asm{ mov Y, A }
	sub A, A, A                                              => asm{ mov TMP, A } @ asm{ sub }
	sub A, A, TMP                                            => asm{ sub }
	sub A, A, B                                              => asm{ mov TMP, B } @ asm{ sub }
	sub A, A, C                                              => asm{ mov TMP, C } @ asm{ sub }
	sub A, A, X                                              => asm{ mov TMP, X } @ asm{ sub }
	sub A, A, Y                                              => asm{ mov TMP, Y } @ asm{ sub }
	sub A, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ sub }
	sub A, TMP, B                                            => asm{ mov A, TMP } @ asm{ mov TMP, B } @ asm{ sub }
	sub A, TMP, C                                            => asm{ mov A, TMP } @ asm{ mov TMP, C } @ asm{ sub }
	sub A, TMP, X                                            => asm{ mov A, TMP } @ asm{ mov TMP, X } @ asm{ sub }
	sub A, TMP, Y                                            => asm{ mov A, TMP } @ asm{ mov TMP, Y } @ asm{ sub }
	sub A, B, A                                              => asm{ mov A, B } @ asm{ mov TMP, A } @ asm{ sub }
	sub A, B, TMP                                            => asm{ mov A, B } @ asm{ sub }
	sub A, B, B                                              => asm{ mov A, B } @ asm{ mov TMP, B } @ asm{ sub }
	sub A, B, C                                              => asm{ mov A, B } @ asm{ mov TMP, C } @ asm{ sub }
	sub A, B, X                                              => asm{ mov A, B } @ asm{ mov TMP, X } @ asm{ sub }
	sub A, B, Y                                              => asm{ mov A, B } @ asm{ mov TMP, Y } @ asm{ sub }
	sub A, C, A                                              => asm{ mov A, C } @ asm{ mov TMP, A } @ asm{ sub }
	sub A, C, TMP                                            => asm{ mov A, C } @ asm{ sub }
	sub A, C, B                                              => asm{ mov A, C } @ asm{ mov TMP, B } @ asm{ sub }
	sub A, C, C                                              => asm{ mov A, C } @ asm{ mov TMP, C } @ asm{ sub }
	sub A, C, X                                              => asm{ mov A, C } @ asm{ mov TMP, X } @ asm{ sub }
	sub A, C, Y                                              => asm{ mov A, C } @ asm{ mov TMP, Y } @ asm{ sub }
	sub A, X, A                                              => asm{ mov A, X } @ asm{ mov TMP, A } @ asm{ sub }
	sub A, X, TMP                                            => asm{ mov A, X } @ asm{ sub }
	sub A, X, B                                              => asm{ mov A, X } @ asm{ mov TMP, B } @ asm{ sub }
	sub A, X, C                                              => asm{ mov A, X } @ asm{ mov TMP, C } @ asm{ sub }
	sub A, X, X                                              => asm{ mov A, X } @ asm{ mov TMP, X } @ asm{ sub }
	sub A, X, Y                                              => asm{ mov A, X } @ asm{ mov TMP, Y } @ asm{ sub }
	sub A, Y, A                                              => asm{ mov A, Y } @ asm{ mov TMP, A } @ asm{ sub }
	sub A, Y, TMP                                            => asm{ mov A, Y } @ asm{ sub }
	sub A, Y, B                                              => asm{ mov A, Y } @ asm{ mov TMP, B } @ asm{ sub }
	sub A, Y, C                                              => asm{ mov A, Y } @ asm{ mov TMP, C } @ asm{ sub }
	sub A, Y, X                                              => asm{ mov A, Y } @ asm{ mov TMP, X } @ asm{ sub }
	sub A, Y, Y                                              => asm{ mov A, Y } @ asm{ mov TMP, Y } @ asm{ sub }
	sub TMP, A, A                                            => asm{ mov TMP, A } @ asm{ sub } @ asm{ mov TMP, A }
	sub TMP, A, TMP                                          => asm{ sub } @ asm{ mov TMP, A }
	sub TMP, A, B                                            => asm{ mov TMP, B } @ asm{ sub } @ asm{ mov TMP, A }
	sub TMP, A, C                                            => asm{ mov TMP, C } @ asm{ sub } @ asm{ mov TMP, A }
	sub TMP, A, X                                            => asm{ mov TMP, X } @ asm{ sub } @ asm{ mov TMP, A }
	sub TMP, A, Y                                            => asm{ mov TMP, Y } @ asm{ sub } @ asm{ mov TMP, A }
	sub TMP, TMP, A                                          => asm{ mov BUF, A } @ asm{ mov A, TMP } @ asm{ mov TMP, BUF } @ asm{ sub } @ asm{ mov TMP, A }
	sub TMP, TMP, TMP                                        => asm{ mov A, TMP } @ asm{ sub } @ asm{ mov TMP, A }
	sub TMP, B, TMP                                          => asm{ mov A, B } @ asm{ sub } @ asm{ mov TMP, A }
	sub TMP, C, TMP                                          => asm{ mov A, C } @ asm{ sub } @ asm{ mov TMP, A }
	sub TMP, X, TMP                                          => asm{ mov A, X } @ asm{ sub } @ asm{ mov TMP, A }
	sub TMP, Y, TMP                                          => asm{ mov A, Y } @ asm{ sub } @ asm{ mov TMP, A }
	sub B, A, A                                              => asm{ mov TMP, A } @ asm{ sub } @ asm{ mov B, A }
	sub B, A, TMP                                            => asm{ sub } @ asm{ mov B, A }
	sub B, A, B                                              => asm{ mov TMP, B } @ asm{ sub } @ asm{ mov B, A }
	sub B, A, C                                              => asm{ mov TMP, C } @ asm{ sub } @ asm{ mov B, A }
	sub B, A, X                                              => asm{ mov TMP, X } @ asm{ sub } @ asm{ mov B, A }
	sub B, A, Y                                              => asm{ mov TMP, Y } @ asm{ sub } @ asm{ mov B, A }
	sub B, TMP, A                                            => asm{ mov BUF, A } @ asm{ mov A, TMP } @ asm{ mov TMP, BUF } @ asm{ sub } @ asm{ mov B, A }
	sub B, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ sub } @ asm{ mov B, A }
	sub B, B, TMP                                            => asm{ mov A, B } @ asm{ sub } @ asm{ mov B, A }
	sub B, C, TMP                                            => asm{ mov A, C } @ asm{ sub } @ asm{ mov B, A }
	sub B, X, TMP                                            => asm{ mov A, X } @ asm{ sub } @ asm{ mov B, A }
	sub B, Y, TMP                                            => asm{ mov A, Y } @ asm{ sub } @ asm{ mov B, A }
	sub C, A, A                                              => asm{ mov TMP, A } @ asm{ sub } @ asm{ mov C, A }
	sub C, A, TMP                                            => asm{ sub } @ asm{ mov C, A }
	sub C, A, B                                              => asm{ mov TMP, B } @ asm{ sub } @ asm{ mov C, A }
	sub C, A, C                                              => asm{ mov TMP, C } @ asm{ sub } @ asm{ mov C, A }
	sub C, A, X                                              => asm{ mov TMP, X } @ asm{ sub } @ asm{ mov C, A }
	sub C, A, Y                                              => asm{ mov TMP, Y } @ asm{ sub } @ asm{ mov C, A }
	sub C, TMP, A                                            => asm{ mov BUF, A } @ asm{ mov A, TMP } @ asm{ mov TMP, BUF } @ asm{ sub } @ asm{ mov C, A }
	sub C, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ sub } @ asm{ mov C, A }
	sub C, B, TMP                                            => asm{ mov A, B } @ asm{ sub } @ asm{ mov C, A }
	sub C, C, TMP                                            => asm{ mov A, C } @ asm{ sub } @ asm{ mov C, A }
	sub C, X, TMP                                            => asm{ mov A, X } @ asm{ sub } @ asm{ mov C, A }
	sub C, Y, TMP                                            => asm{ mov A, Y } @ asm{ sub } @ asm{ mov C, A }
	sub X, A, A                                              => asm{ mov TMP, A } @ asm{ sub } @ asm{ mov X, A }
	sub X, A, TMP                                            => asm{ sub } @ asm{ mov X, A }
	sub X, A, B                                              => asm{ mov TMP, B } @ asm{ sub } @ asm{ mov X, A }
	sub X, A, C                                              => asm{ mov TMP, C } @ asm{ sub } @ asm{ mov X, A }
	sub X, A, X                                              => asm{ mov TMP, X } @ asm{ sub } @ asm{ mov X, A }
	sub X, A, Y                                              => asm{ mov TMP, Y } @ asm{ sub } @ asm{ mov X, A }
	sub X, TMP, A                                            => asm{ mov BUF, A } @ asm{ mov A, TMP } @ asm{ mov TMP, BUF } @ asm{ sub } @ asm{ mov X, A }
	sub X, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ sub } @ asm{ mov X, A }
	sub X, B, TMP                                            => asm{ mov A, B } @ asm{ sub } @ asm{ mov X, A }
	sub X, C, TMP                                            => asm{ mov A, C } @ asm{ sub } @ asm{ mov X, A }
	sub X, X, TMP                                            => asm{ mov A, X } @ asm{ sub } @ asm{ mov X, A }
	sub X, Y, TMP                                            => asm{ mov A, Y } @ asm{ sub } @ asm{ mov X, A }
	sub Y, A, A                                              => asm{ mov TMP, A } @ asm{ sub } @ asm{ mov Y, A }
	sub Y, A, TMP                                            => asm{ sub } @ asm{ mov Y, A }
	sub Y, A, B                                              => asm{ mov TMP, B } @ asm{ sub } @ asm{ mov Y, A }
	sub Y, A, C                                              => asm{ mov TMP, C } @ asm{ sub } @ asm{ mov Y, A }
	sub Y, A, X                                              => asm{ mov TMP, X } @ asm{ sub } @ asm{ mov Y, A }
	sub Y, A, Y                                              => asm{ mov TMP, Y } @ asm{ sub } @ asm{ mov Y, A }
	sub Y, TMP, A                                            => asm{ mov BUF, A } @ asm{ mov A, TMP } @ asm{ mov TMP, BUF } @ asm{ sub } @ asm{ mov Y, A }
	sub Y, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ sub } @ asm{ mov Y, A }
	sub Y, B, TMP                                            => asm{ mov A, B } @ asm{ sub } @ asm{ mov Y, A }
	sub Y, C, TMP                                            => asm{ mov A, C } @ asm{ sub } @ asm{ mov Y, A }
	sub Y, X, TMP                                            => asm{ mov A, X } @ asm{ sub } @ asm{ mov Y, A }
	sub Y, Y, TMP                                            => asm{ mov A, Y } @ asm{ sub } @ asm{ mov Y, A }
	subc A, A, A                                             => asm{ mov TMP, A } @ asm{ subc }
	subc A, A, TMP                                           => asm{ subc }
	subc A, A, B                                             => asm{ mov TMP, B } @ asm{ subc }
	subc A, A, C                                             => asm{ mov TMP, C } @ asm{ subc }
	subc A, A, X                                             => asm{ mov TMP, X } @ asm{ subc }
	subc A, A, Y                                             => asm{ mov TMP, Y } @ asm{ subc }
	subc A, TMP, TMP                                         => asm{ mov A, TMP } @ asm{ subc }
	subc A, TMP, B                                           => asm{ mov A, TMP } @ asm{ mov TMP, B } @ asm{ subc }
	subc A, TMP, C                                           => asm{ mov A, TMP } @ asm{ mov TMP, C } @ asm{ subc }
	subc A, TMP, X                                           => asm{ mov A, TMP } @ asm{ mov TMP, X } @ asm{ subc }
	subc A, TMP, Y                                           => asm{ mov A, TMP } @ asm{ mov TMP, Y } @ asm{ subc }
	subc A, B, A                                             => asm{ mov A, B } @ asm{ mov TMP, A } @ asm{ subc }
	subc A, B, TMP                                           => asm{ mov A, B } @ asm{ subc }
	subc A, B, B                                             => asm{ mov A, B } @ asm{ mov TMP, B } @ asm{ subc }
	subc A, B, C                                             => asm{ mov A, B } @ asm{ mov TMP, C } @ asm{ subc }
	subc A, B, X                                             => asm{ mov A, B } @ asm{ mov TMP, X } @ asm{ subc }
	subc A, B, Y                                             => asm{ mov A, B } @ asm{ mov TMP, Y } @ asm{ subc }
	subc A, C, A                                             => asm{ mov A, C } @ asm{ mov TMP, A } @ asm{ subc }
	subc A, C, TMP                                           => asm{ mov A, C } @ asm{ subc }
	subc A, C, B                                             => asm{ mov A, C } @ asm{ mov TMP, B } @ asm{ subc }
	subc A, C, C                                             => asm{ mov A, C } @ asm{ mov TMP, C } @ asm{ subc }
	subc A, C, X                                             => asm{ mov A, C } @ asm{ mov TMP, X } @ asm{ subc }
	subc A, C, Y                                             => asm{ mov A, C } @ asm{ mov TMP, Y } @ asm{ subc }
	subc A, X, A                                             => asm{ mov A, X } @ asm{ mov TMP, A } @ asm{ subc }
	subc A, X, TMP                                           => asm{ mov A, X } @ asm{ subc }
	subc A, X, B                                             => asm{ mov A, X } @ asm{ mov TMP, B } @ asm{ subc }
	subc A, X, C                                             => asm{ mov A, X } @ asm{ mov TMP, C } @ asm{ subc }
	subc A, X, X                                             => asm{ mov A, X } @ asm{ mov TMP, X } @ asm{ subc }
	subc A, X, Y                                             => asm{ mov A, X } @ asm{ mov TMP, Y } @ asm{ subc }
	subc A, Y, A                                             => asm{ mov A, Y } @ asm{ mov TMP, A } @ asm{ subc }
	subc A, Y, TMP                                           => asm{ mov A, Y } @ asm{ subc }
	subc A, Y, B                                             => asm{ mov A, Y } @ asm{ mov TMP, B } @ asm{ subc }
	subc A, Y, C                                             => asm{ mov A, Y } @ asm{ mov TMP, C } @ asm{ subc }
	subc A, Y, X                                             => asm{ mov A, Y } @ asm{ mov TMP, X } @ asm{ subc }
	subc A, Y, Y                                             => asm{ mov A, Y } @ asm{ mov TMP, Y } @ asm{ subc }
	subc TMP, A, A                                           => asm{ mov TMP, A } @ asm{ subc } @ asm{ mov TMP, A }
	subc TMP, A, TMP                                         => asm{ subc } @ asm{ mov TMP, A }
	subc TMP, A, B                                           => asm{ mov TMP, B } @ asm{ subc } @ asm{ mov TMP, A }
	subc TMP, A, C                                           => asm{ mov TMP, C } @ asm{ subc } @ asm{ mov TMP, A }
	subc TMP, A, X                                           => asm{ mov TMP, X } @ asm{ subc } @ asm{ mov TMP, A }
	subc TMP, A, Y                                           => asm{ mov TMP, Y } @ asm{ subc } @ asm{ mov TMP, A }
	subc TMP, TMP, A                                         => asm{ mov BUF, A } @ asm{ mov A, TMP } @ asm{ mov TMP, BUF } @ asm{ subc } @ asm{ mov TMP, A }
	subc TMP, TMP, TMP                                       => asm{ mov A, TMP } @ asm{ subc } @ asm{ mov TMP, A }
	subc TMP, B, TMP                                         => asm{ mov A, B } @ asm{ subc } @ asm{ mov TMP, A }
	subc TMP, C, TMP                                         => asm{ mov A, C } @ asm{ subc } @ asm{ mov TMP, A }
	subc TMP, X, TMP                                         => asm{ mov A, X } @ asm{ subc } @ asm{ mov TMP, A }
	subc TMP, Y, TMP                                         => asm{ mov A, Y } @ asm{ subc } @ asm{ mov TMP, A }
	subc B, A, A                                             => asm{ mov TMP, A } @ asm{ subc } @ asm{ mov B, A }
	subc B, A, TMP                                           => asm{ subc } @ asm{ mov B, A }
	subc B, A, B                                             => asm{ mov TMP, B } @ asm{ subc } @ asm{ mov B, A }
	subc B, A, C                                             => asm{ mov TMP, C } @ asm{ subc } @ asm{ mov B, A }
	subc B, A, X                                             => asm{ mov TMP, X } @ asm{ subc } @ asm{ mov B, A }
	subc B, A, Y                                             => asm{ mov TMP, Y } @ asm{ subc } @ asm{ mov B, A }
	subc B, TMP, A                                           => asm{ mov BUF, A } @ asm{ mov A, TMP } @ asm{ mov TMP, BUF } @ asm{ subc } @ asm{ mov B, A }
	subc B, TMP, TMP                                         => asm{ mov A, TMP } @ asm{ subc } @ asm{ mov B, A }
	subc B, B, TMP                                           => asm{ mov A, B } @ asm{ subc } @ asm{ mov B, A }
	subc B, C, TMP                                           => asm{ mov A, C } @ asm{ subc } @ asm{ mov B, A }
	subc B, X, TMP                                           => asm{ mov A, X } @ asm{ subc } @ asm{ mov B, A }
	subc B, Y, TMP                                           => asm{ mov A, Y } @ asm{ subc } @ asm{ mov B, A }
	subc C, A, A                                             => asm{ mov TMP, A } @ asm{ subc } @ asm{ mov C, A }
	subc C, A, TMP                                           => asm{ subc } @ asm{ mov C, A }
	subc C, A, B                                             => asm{ mov TMP, B } @ asm{ subc } @ asm{ mov C, A }
	subc C, A, C                                             => asm{ mov TMP, C } @ asm{ subc } @ asm{ mov C, A }
	subc C, A, X                                             => asm{ mov TMP, X } @ asm{ subc } @ asm{ mov C, A }
	subc C, A, Y                                             => asm{ mov TMP, Y } @ asm{ subc } @ asm{ mov C, A }
	subc C, TMP, A                                           => asm{ mov BUF, A } @ asm{ mov A, TMP } @ asm{ mov TMP, BUF } @ asm{ subc } @ asm{ mov C, A }
	subc C, TMP, TMP                                         => asm{ mov A, TMP } @ asm{ subc } @ asm{ mov C, A }
	subc C, B, TMP                                           => asm{ mov A, B } @ asm{ subc } @ asm{ mov C, A }
	subc C, C, TMP                                           => asm{ mov A, C } @ asm{ subc } @ asm{ mov C, A }
	subc C, X, TMP                                           => asm{ mov A, X } @ asm{ subc } @ asm{ mov C, A }
	subc C, Y, TMP                                           => asm{ mov A, Y } @ asm{ subc } @ asm{ mov C, A }
	subc X, A, A                                             => asm{ mov TMP, A } @ asm{ subc } @ asm{ mov X, A }
	subc X, A, TMP                                           => asm{ subc } @ asm{ mov X, A }
	subc X, A, B                                             => asm{ mov TMP, B } @ asm{ subc } @ asm{ mov X, A }
	subc X, A, C                                             => asm{ mov TMP, C } @ asm{ subc } @ asm{ mov X, A }
	subc X, A, X                                             => asm{ mov TMP, X } @ asm{ subc } @ asm{ mov X, A }
	subc X, A, Y                                             => asm{ mov TMP, Y } @ asm{ subc } @ asm{ mov X, A }
	subc X, TMP, A                                           => asm{ mov BUF, A } @ asm{ mov A, TMP } @ asm{ mov TMP, BUF } @ asm{ subc } @ asm{ mov X, A }
	subc X, TMP, TMP                                         => asm{ mov A, TMP } @ asm{ subc } @ asm{ mov X, A }
	subc X, B, TMP                                           => asm{ mov A, B } @ asm{ subc } @ asm{ mov X, A }
	subc X, C, TMP                                           => asm{ mov A, C } @ asm{ subc } @ asm{ mov X, A }
	subc X, X, TMP                                           => asm{ mov A, X } @ asm{ subc } @ asm{ mov X, A }
	subc X, Y, TMP                                           => asm{ mov A, Y } @ asm{ subc } @ asm{ mov X, A }
	subc Y, A, A                                             => asm{ mov TMP, A } @ asm{ subc } @ asm{ mov Y, A }
	subc Y, A, TMP                                           => asm{ subc } @ asm{ mov Y, A }
	subc Y, A, B                                             => asm{ mov TMP, B } @ asm{ subc } @ asm{ mov Y, A }
	subc Y, A, C                                             => asm{ mov TMP, C } @ asm{ subc } @ asm{ mov Y, A }
	subc Y, A, X                                             => asm{ mov TMP, X } @ asm{ subc } @ asm{ mov Y, A }
	subc Y, A, Y                                             => asm{ mov TMP, Y } @ asm{ subc } @ asm{ mov Y, A }
	subc Y, TMP, A                                           => asm{ mov BUF, A } @ asm{ mov A, TMP } @ asm{ mov TMP, BUF } @ asm{ subc } @ asm{ mov Y, A }
	subc Y, TMP, TMP                                         => asm{ mov A, TMP } @ asm{ subc } @ asm{ mov Y, A }
	subc Y, B, TMP                                           => asm{ mov A, B } @ asm{ subc } @ asm{ mov Y, A }
	subc Y, C, TMP                                           => asm{ mov A, C } @ asm{ subc } @ asm{ mov Y, A }
	subc Y, X, TMP                                           => asm{ mov A, X } @ asm{ subc } @ asm{ mov Y, A }
	subc Y, Y, TMP                                           => asm{ mov A, Y } @ asm{ subc } @ asm{ mov Y, A }
	and {reg1: register}, {reg2: register}, {reg3: register} => asm{ mov A, {reg2} } @ asm{ mov TMP, {reg3} } @ asm{ and } @ asm{ mov {reg1}, A }
	and A, A, A                                              => asm{ mov TMP, A } @ asm{ and }
	and A, A, TMP                                            => asm{ and }
	and A, A, B                                              => asm{ mov TMP, B } @ asm{ and }
	and A, A, C                                              => asm{ mov TMP, C } @ asm{ and }
	and A, A, X                                              => asm{ mov TMP, X } @ asm{ and }
	and A, A, Y                                              => asm{ mov TMP, Y } @ asm{ and }
	and A, TMP, A                                            => asm{ mov A, TMP } @ asm{ mov TMP, A } @ asm{ and }
	and A, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ and }
	and A, TMP, B                                            => asm{ mov A, TMP } @ asm{ mov TMP, B } @ asm{ and }
	and A, TMP, C                                            => asm{ mov A, TMP } @ asm{ mov TMP, C } @ asm{ and }
	and A, TMP, X                                            => asm{ mov A, TMP } @ asm{ mov TMP, X } @ asm{ and }
	and A, TMP, Y                                            => asm{ mov A, TMP } @ asm{ mov TMP, Y } @ asm{ and }
	and A, B, A                                              => asm{ mov A, B } @ asm{ mov TMP, A } @ asm{ and }
	and A, B, TMP                                            => asm{ mov A, B } @ asm{ and }
	and A, B, B                                              => asm{ mov A, B } @ asm{ mov TMP, B } @ asm{ and }
	and A, B, C                                              => asm{ mov A, B } @ asm{ mov TMP, C } @ asm{ and }
	and A, B, X                                              => asm{ mov A, B } @ asm{ mov TMP, X } @ asm{ and }
	and A, B, Y                                              => asm{ mov A, B } @ asm{ mov TMP, Y } @ asm{ and }
	and A, C, A                                              => asm{ mov A, C } @ asm{ mov TMP, A } @ asm{ and }
	and A, C, TMP                                            => asm{ mov A, C } @ asm{ and }
	and A, C, B                                              => asm{ mov A, C } @ asm{ mov TMP, B } @ asm{ and }
	and A, C, C                                              => asm{ mov A, C } @ asm{ mov TMP, C } @ asm{ and }
	and A, C, X                                              => asm{ mov A, C } @ asm{ mov TMP, X } @ asm{ and }
	and A, C, Y                                              => asm{ mov A, C } @ asm{ mov TMP, Y } @ asm{ and }
	and A, X, A                                              => asm{ mov A, X } @ asm{ mov TMP, A } @ asm{ and }
	and A, X, TMP                                            => asm{ mov A, X } @ asm{ and }
	and A, X, B                                              => asm{ mov A, X } @ asm{ mov TMP, B } @ asm{ and }
	and A, X, C                                              => asm{ mov A, X } @ asm{ mov TMP, C } @ asm{ and }
	and A, X, X                                              => asm{ mov A, X } @ asm{ mov TMP, X } @ asm{ and }
	and A, X, Y                                              => asm{ mov A, X } @ asm{ mov TMP, Y } @ asm{ and }
	and A, Y, A                                              => asm{ mov A, Y } @ asm{ mov TMP, A } @ asm{ and }
	and A, Y, TMP                                            => asm{ mov A, Y } @ asm{ and }
	and A, Y, B                                              => asm{ mov A, Y } @ asm{ mov TMP, B } @ asm{ and }
	and A, Y, C                                              => asm{ mov A, Y } @ asm{ mov TMP, C } @ asm{ and }
	and A, Y, X                                              => asm{ mov A, Y } @ asm{ mov TMP, X } @ asm{ and }
	and A, Y, Y                                              => asm{ mov A, Y } @ asm{ mov TMP, Y } @ asm{ and }
	and TMP, A, A                                            => asm{ mov TMP, A } @ asm{ and } @ asm{ mov TMP, A }
	and TMP, A, TMP                                          => asm{ and } @ asm{ mov TMP, A }
	and TMP, A, B                                            => asm{ mov TMP, B } @ asm{ and } @ asm{ mov TMP, A }
	and TMP, A, C                                            => asm{ mov TMP, C } @ asm{ and } @ asm{ mov TMP, A }
	and TMP, A, X                                            => asm{ mov TMP, X } @ asm{ and } @ asm{ mov TMP, A }
	and TMP, A, Y                                            => asm{ mov TMP, Y } @ asm{ and } @ asm{ mov TMP, A }
	and TMP, TMP, TMP                                        => asm{ mov A, TMP } @ asm{ and } @ asm{ mov TMP, A }
	and TMP, B, TMP                                          => asm{ mov A, B } @ asm{ and } @ asm{ mov TMP, A }
	and TMP, C, TMP                                          => asm{ mov A, C } @ asm{ and } @ asm{ mov TMP, A }
	and TMP, X, TMP                                          => asm{ mov A, X } @ asm{ and } @ asm{ mov TMP, A }
	and TMP, Y, TMP                                          => asm{ mov A, Y } @ asm{ and } @ asm{ mov TMP, A }
	and B, A, A                                              => asm{ mov TMP, A } @ asm{ and } @ asm{ mov B, A }
	and B, A, TMP                                            => asm{ and } @ asm{ mov B, A }
	and B, A, B                                              => asm{ mov TMP, B } @ asm{ and } @ asm{ mov B, A }
	and B, A, C                                              => asm{ mov TMP, C } @ asm{ and } @ asm{ mov B, A }
	and B, A, X                                              => asm{ mov TMP, X } @ asm{ and } @ asm{ mov B, A }
	and B, A, Y                                              => asm{ mov TMP, Y } @ asm{ and } @ asm{ mov B, A }
	and B, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ and } @ asm{ mov B, A }
	and B, B, TMP                                            => asm{ mov A, B } @ asm{ and } @ asm{ mov B, A }
	and B, C, TMP                                            => asm{ mov A, C } @ asm{ and } @ asm{ mov B, A }
	and B, X, TMP                                            => asm{ mov A, X } @ asm{ and } @ asm{ mov B, A }
	and B, Y, TMP                                            => asm{ mov A, Y } @ asm{ and } @ asm{ mov B, A }
	and C, A, A                                              => asm{ mov TMP, A } @ asm{ and } @ asm{ mov C, A }
	and C, A, TMP                                            => asm{ and } @ asm{ mov C, A }
	and C, A, B                                              => asm{ mov TMP, B } @ asm{ and } @ asm{ mov C, A }
	and C, A, C                                              => asm{ mov TMP, C } @ asm{ and } @ asm{ mov C, A }
	and C, A, X                                              => asm{ mov TMP, X } @ asm{ and } @ asm{ mov C, A }
	and C, A, Y                                              => asm{ mov TMP, Y } @ asm{ and } @ asm{ mov C, A }
	and C, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ and } @ asm{ mov C, A }
	and C, B, TMP                                            => asm{ mov A, B } @ asm{ and } @ asm{ mov C, A }
	and C, C, TMP                                            => asm{ mov A, C } @ asm{ and } @ asm{ mov C, A }
	and C, X, TMP                                            => asm{ mov A, X } @ asm{ and } @ asm{ mov C, A }
	and C, Y, TMP                                            => asm{ mov A, Y } @ asm{ and } @ asm{ mov C, A }
	and X, A, A                                              => asm{ mov TMP, A } @ asm{ and } @ asm{ mov X, A }
	and X, A, TMP                                            => asm{ and } @ asm{ mov X, A }
	and X, A, B                                              => asm{ mov TMP, B } @ asm{ and } @ asm{ mov X, A }
	and X, A, C                                              => asm{ mov TMP, C } @ asm{ and } @ asm{ mov X, A }
	and X, A, X                                              => asm{ mov TMP, X } @ asm{ and } @ asm{ mov X, A }
	and X, A, Y                                              => asm{ mov TMP, Y } @ asm{ and } @ asm{ mov X, A }
	and X, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ and } @ asm{ mov X, A }
	and X, B, TMP                                            => asm{ mov A, B } @ asm{ and } @ asm{ mov X, A }
	and X, C, TMP                                            => asm{ mov A, C } @ asm{ and } @ asm{ mov X, A }
	and X, X, TMP                                            => asm{ mov A, X } @ asm{ and } @ asm{ mov X, A }
	and X, Y, TMP                                            => asm{ mov A, Y } @ asm{ and } @ asm{ mov X, A }
	and Y, A, A                                              => asm{ mov TMP, A } @ asm{ and } @ asm{ mov Y, A }
	and Y, A, TMP                                            => asm{ and } @ asm{ mov Y, A }
	and Y, A, B                                              => asm{ mov TMP, B } @ asm{ and } @ asm{ mov Y, A }
	and Y, A, C                                              => asm{ mov TMP, C } @ asm{ and } @ asm{ mov Y, A }
	and Y, A, X                                              => asm{ mov TMP, X } @ asm{ and } @ asm{ mov Y, A }
	and Y, A, Y                                              => asm{ mov TMP, Y } @ asm{ and } @ asm{ mov Y, A }
	and Y, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ and } @ asm{ mov Y, A }
	and Y, B, TMP                                            => asm{ mov A, B } @ asm{ and } @ asm{ mov Y, A }
	and Y, C, TMP                                            => asm{ mov A, C } @ asm{ and } @ asm{ mov Y, A }
	and Y, X, TMP                                            => asm{ mov A, X } @ asm{ and } @ asm{ mov Y, A }
	and Y, Y, TMP                                            => asm{ mov A, Y } @ asm{ and } @ asm{ mov Y, A }
	or {reg1: register}, {reg2: register}, {reg3: register}  => asm{ mov A, {reg2} } @ asm{ mov TMP, {reg3} } @ asm{ or } @ asm{ mov {reg1}, A }
	or A, A, A                                               => asm{ mov TMP, A } @ asm{ or }
	or A, A, TMP                                             => asm{ or }
	or A, A, B                                               => asm{ mov TMP, B } @ asm{ or }
	or A, A, C                                               => asm{ mov TMP, C } @ asm{ or }
	or A, A, X                                               => asm{ mov TMP, X } @ asm{ or }
	or A, A, Y                                               => asm{ mov TMP, Y } @ asm{ or }
	or A, TMP, A                                             => asm{ mov A, TMP } @ asm{ mov TMP, A } @ asm{ or }
	or A, TMP, TMP                                           => asm{ mov A, TMP } @ asm{ or }
	or A, TMP, B                                             => asm{ mov A, TMP } @ asm{ mov TMP, B } @ asm{ or }
	or A, TMP, C                                             => asm{ mov A, TMP } @ asm{ mov TMP, C } @ asm{ or }
	or A, TMP, X                                             => asm{ mov A, TMP } @ asm{ mov TMP, X } @ asm{ or }
	or A, TMP, Y                                             => asm{ mov A, TMP } @ asm{ mov TMP, Y } @ asm{ or }
	or A, B, A                                               => asm{ mov A, B } @ asm{ mov TMP, A } @ asm{ or }
	or A, B, TMP                                             => asm{ mov A, B } @ asm{ or }
	or A, B, B                                               => asm{ mov A, B } @ asm{ mov TMP, B } @ asm{ or }
	or A, B, C                                               => asm{ mov A, B } @ asm{ mov TMP, C } @ asm{ or }
	or A, B, X                                               => asm{ mov A, B } @ asm{ mov TMP, X } @ asm{ or }
	or A, B, Y                                               => asm{ mov A, B } @ asm{ mov TMP, Y } @ asm{ or }
	or A, C, A                                               => asm{ mov A, C } @ asm{ mov TMP, A } @ asm{ or }
	or A, C, TMP                                             => asm{ mov A, C } @ asm{ or }
	or A, C, B                                               => asm{ mov A, C } @ asm{ mov TMP, B } @ asm{ or }
	or A, C, C                                               => asm{ mov A, C } @ asm{ mov TMP, C } @ asm{ or }
	or A, C, X                                               => asm{ mov A, C } @ asm{ mov TMP, X } @ asm{ or }
	or A, C, Y                                               => asm{ mov A, C } @ asm{ mov TMP, Y } @ asm{ or }
	or A, X, A                                               => asm{ mov A, X } @ asm{ mov TMP, A } @ asm{ or }
	or A, X, TMP                                             => asm{ mov A, X } @ asm{ or }
	or A, X, B                                               => asm{ mov A, X } @ asm{ mov TMP, B } @ asm{ or }
	or A, X, C                                               => asm{ mov A, X } @ asm{ mov TMP, C } @ asm{ or }
	or A, X, X                                               => asm{ mov A, X } @ asm{ mov TMP, X } @ asm{ or }
	or A, X, Y                                               => asm{ mov A, X } @ asm{ mov TMP, Y } @ asm{ or }
	or A, Y, A                                               => asm{ mov A, Y } @ asm{ mov TMP, A } @ asm{ or }
	or A, Y, TMP                                             => asm{ mov A, Y } @ asm{ or }
	or A, Y, B                                               => asm{ mov A, Y } @ asm{ mov TMP, B } @ asm{ or }
	or A, Y, C                                               => asm{ mov A, Y } @ asm{ mov TMP, C } @ asm{ or }
	or A, Y, X                                               => asm{ mov A, Y } @ asm{ mov TMP, X } @ asm{ or }
	or A, Y, Y                                               => asm{ mov A, Y } @ asm{ mov TMP, Y } @ asm{ or }
	or TMP, A, A                                             => asm{ mov TMP, A } @ asm{ or } @ asm{ mov TMP, A }
	or TMP, A, TMP                                           => asm{ or } @ asm{ mov TMP, A }
	or TMP, A, B                                             => asm{ mov TMP, B } @ asm{ or } @ asm{ mov TMP, A }
	or TMP, A, C                                             => asm{ mov TMP, C } @ asm{ or } @ asm{ mov TMP, A }
	or TMP, A, X                                             => asm{ mov TMP, X } @ asm{ or } @ asm{ mov TMP, A }
	or TMP, A, Y                                             => asm{ mov TMP, Y } @ asm{ or } @ asm{ mov TMP, A }
	or TMP, TMP, TMP                                         => asm{ mov A, TMP } @ asm{ or } @ asm{ mov TMP, A }
	or TMP, B, TMP                                           => asm{ mov A, B } @ asm{ or } @ asm{ mov TMP, A }
	or TMP, C, TMP                                           => asm{ mov A, C } @ asm{ or } @ asm{ mov TMP, A }
	or TMP, X, TMP                                           => asm{ mov A, X } @ asm{ or } @ asm{ mov TMP, A }
	or TMP, Y, TMP                                           => asm{ mov A, Y } @ asm{ or } @ asm{ mov TMP, A }
	or B, A, A                                               => asm{ mov TMP, A } @ asm{ or } @ asm{ mov B, A }
	or B, A, TMP                                             => asm{ or } @ asm{ mov B, A }
	or B, A, B                                               => asm{ mov TMP, B } @ asm{ or } @ asm{ mov B, A }
	or B, A, C                                               => asm{ mov TMP, C } @ asm{ or } @ asm{ mov B, A }
	or B, A, X                                               => asm{ mov TMP, X } @ asm{ or } @ asm{ mov B, A }
	or B, A, Y                                               => asm{ mov TMP, Y } @ asm{ or } @ asm{ mov B, A }
	or B, TMP, TMP                                           => asm{ mov A, TMP } @ asm{ or } @ asm{ mov B, A }
	or B, B, TMP                                             => asm{ mov A, B } @ asm{ or } @ asm{ mov B, A }
	or B, C, TMP                                             => asm{ mov A, C } @ asm{ or } @ asm{ mov B, A }
	or B, X, TMP                                             => asm{ mov A, X } @ asm{ or } @ asm{ mov B, A }
	or B, Y, TMP                                             => asm{ mov A, Y } @ asm{ or } @ asm{ mov B, A }
	or C, A, A                                               => asm{ mov TMP, A } @ asm{ or } @ asm{ mov C, A }
	or C, A, TMP                                             => asm{ or } @ asm{ mov C, A }
	or C, A, B                                               => asm{ mov TMP, B } @ asm{ or } @ asm{ mov C, A }
	or C, A, C                                               => asm{ mov TMP, C } @ asm{ or } @ asm{ mov C, A }
	or C, A, X                                               => asm{ mov TMP, X } @ asm{ or } @ asm{ mov C, A }
	or C, A, Y                                               => asm{ mov TMP, Y } @ asm{ or } @ asm{ mov C, A }
	or C, TMP, TMP                                           => asm{ mov A, TMP } @ asm{ or } @ asm{ mov C, A }
	or C, B, TMP                                             => asm{ mov A, B } @ asm{ or } @ asm{ mov C, A }
	or C, C, TMP                                             => asm{ mov A, C } @ asm{ or } @ asm{ mov C, A }
	or C, X, TMP                                             => asm{ mov A, X } @ asm{ or } @ asm{ mov C, A }
	or C, Y, TMP                                             => asm{ mov A, Y } @ asm{ or } @ asm{ mov C, A }
	or X, A, A                                               => asm{ mov TMP, A } @ asm{ or } @ asm{ mov X, A }
	or X, A, TMP                                             => asm{ or } @ asm{ mov X, A }
	or X, A, B                                               => asm{ mov TMP, B } @ asm{ or } @ asm{ mov X, A }
	or X, A, C                                               => asm{ mov TMP, C } @ asm{ or } @ asm{ mov X, A }
	or X, A, X                                               => asm{ mov TMP, X } @ asm{ or } @ asm{ mov X, A }
	or X, A, Y                                               => asm{ mov TMP, Y } @ asm{ or } @ asm{ mov X, A }
	or X, TMP, TMP                                           => asm{ mov A, TMP } @ asm{ or } @ asm{ mov X, A }
	or X, B, TMP                                             => asm{ mov A, B } @ asm{ or } @ asm{ mov X, A }
	or X, C, TMP                                             => asm{ mov A, C } @ asm{ or } @ asm{ mov X, A }
	or X, X, TMP                                             => asm{ mov A, X } @ asm{ or } @ asm{ mov X, A }
	or X, Y, TMP                                             => asm{ mov A, Y } @ asm{ or } @ asm{ mov X, A }
	or Y, A, A                                               => asm{ mov TMP, A } @ asm{ or } @ asm{ mov Y, A }
	or Y, A, TMP                                             => asm{ or } @ asm{ mov Y, A }
	or Y, A, B                                               => asm{ mov TMP, B } @ asm{ or } @ asm{ mov Y, A }
	or Y, A, C                                               => asm{ mov TMP, C } @ asm{ or } @ asm{ mov Y, A }
	or Y, A, X                                               => asm{ mov TMP, X } @ asm{ or } @ asm{ mov Y, A }
	or Y, A, Y                                               => asm{ mov TMP, Y } @ asm{ or } @ asm{ mov Y, A }
	or Y, TMP, TMP                                           => asm{ mov A, TMP } @ asm{ or } @ asm{ mov Y, A }
	or Y, B, TMP                                             => asm{ mov A, B } @ asm{ or } @ asm{ mov Y, A }
	or Y, C, TMP                                             => asm{ mov A, C } @ asm{ or } @ asm{ mov Y, A }
	or Y, X, TMP                                             => asm{ mov A, X } @ asm{ or } @ asm{ mov Y, A }
	or Y, Y, TMP                                             => asm{ mov A, Y } @ asm{ or } @ asm{ mov Y, A }
	xor {reg1: register}, {reg2: register}, {reg3: register} => asm{ mov A, {reg2} } @ asm{ mov TMP, {reg3} } @ asm{ xor } @ asm{ mov {reg1}, A }
	xor A, A, A                                              => asm{ mov TMP, A } @ asm{ xor }
	xor A, A, TMP                                            => asm{ xor }
	xor A, A, B                                              => asm{ mov TMP, B } @ asm{ xor }
	xor A, A, C                                              => asm{ mov TMP, C } @ asm{ xor }
	xor A, A, X                                              => asm{ mov TMP, X } @ asm{ xor }
	xor A, A, Y                                              => asm{ mov TMP, Y } @ asm{ xor }
	xor A, TMP, A                                            => asm{ mov A, TMP } @ asm{ mov TMP, A } @ asm{ xor }
	xor A, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ xor }
	xor A, TMP, B                                            => asm{ mov A, TMP } @ asm{ mov TMP, B } @ asm{ xor }
	xor A, TMP, C                                            => asm{ mov A, TMP } @ asm{ mov TMP, C } @ asm{ xor }
	xor A, TMP, X                                            => asm{ mov A, TMP } @ asm{ mov TMP, X } @ asm{ xor }
	xor A, TMP, Y                                            => asm{ mov A, TMP } @ asm{ mov TMP, Y } @ asm{ xor }
	xor A, B, A                                              => asm{ mov A, B } @ asm{ mov TMP, A } @ asm{ xor }
	xor A, B, TMP                                            => asm{ mov A, B } @ asm{ xor }
	xor A, B, B                                              => asm{ mov A, B } @ asm{ mov TMP, B } @ asm{ xor }
	xor A, B, C                                              => asm{ mov A, B } @ asm{ mov TMP, C } @ asm{ xor }
	xor A, B, X                                              => asm{ mov A, B } @ asm{ mov TMP, X } @ asm{ xor }
	xor A, B, Y                                              => asm{ mov A, B } @ asm{ mov TMP, Y } @ asm{ xor }
	xor A, C, A                                              => asm{ mov A, C } @ asm{ mov TMP, A } @ asm{ xor }
	xor A, C, TMP                                            => asm{ mov A, C } @ asm{ xor }
	xor A, C, B                                              => asm{ mov A, C } @ asm{ mov TMP, B } @ asm{ xor }
	xor A, C, C                                              => asm{ mov A, C } @ asm{ mov TMP, C } @ asm{ xor }
	xor A, C, X                                              => asm{ mov A, C } @ asm{ mov TMP, X } @ asm{ xor }
	xor A, C, Y                                              => asm{ mov A, C } @ asm{ mov TMP, Y } @ asm{ xor }
	xor A, X, A                                              => asm{ mov A, X } @ asm{ mov TMP, A } @ asm{ xor }
	xor A, X, TMP                                            => asm{ mov A, X } @ asm{ xor }
	xor A, X, B                                              => asm{ mov A, X } @ asm{ mov TMP, B } @ asm{ xor }
	xor A, X, C                                              => asm{ mov A, X } @ asm{ mov TMP, C } @ asm{ xor }
	xor A, X, X                                              => asm{ mov A, X } @ asm{ mov TMP, X } @ asm{ xor }
	xor A, X, Y                                              => asm{ mov A, X } @ asm{ mov TMP, Y } @ asm{ xor }
	xor A, Y, A                                              => asm{ mov A, Y } @ asm{ mov TMP, A } @ asm{ xor }
	xor A, Y, TMP                                            => asm{ mov A, Y } @ asm{ xor }
	xor A, Y, B                                              => asm{ mov A, Y } @ asm{ mov TMP, B } @ asm{ xor }
	xor A, Y, C                                              => asm{ mov A, Y } @ asm{ mov TMP, C } @ asm{ xor }
	xor A, Y, X                                              => asm{ mov A, Y } @ asm{ mov TMP, X } @ asm{ xor }
	xor A, Y, Y                                              => asm{ mov A, Y } @ asm{ mov TMP, Y } @ asm{ xor }
	xor TMP, A, A                                            => asm{ mov TMP, A } @ asm{ xor } @ asm{ mov TMP, A }
	xor TMP, A, TMP                                          => asm{ xor } @ asm{ mov TMP, A }
	xor TMP, A, B                                            => asm{ mov TMP, B } @ asm{ xor } @ asm{ mov TMP, A }
	xor TMP, A, C                                            => asm{ mov TMP, C } @ asm{ xor } @ asm{ mov TMP, A }
	xor TMP, A, X                                            => asm{ mov TMP, X } @ asm{ xor } @ asm{ mov TMP, A }
	xor TMP, A, Y                                            => asm{ mov TMP, Y } @ asm{ xor } @ asm{ mov TMP, A }
	xor TMP, TMP, TMP                                        => asm{ mov A, TMP } @ asm{ xor } @ asm{ mov TMP, A }
	xor TMP, B, TMP                                          => asm{ mov A, B } @ asm{ xor } @ asm{ mov TMP, A }
	xor TMP, C, TMP                                          => asm{ mov A, C } @ asm{ xor } @ asm{ mov TMP, A }
	xor TMP, X, TMP                                          => asm{ mov A, X } @ asm{ xor } @ asm{ mov TMP, A }
	xor TMP, Y, TMP                                          => asm{ mov A, Y } @ asm{ xor } @ asm{ mov TMP, A }
	xor B, A, A                                              => asm{ mov TMP, A } @ asm{ xor } @ asm{ mov B, A }
	xor B, A, TMP                                            => asm{ xor } @ asm{ mov B, A }
	xor B, A, B                                              => asm{ mov TMP, B } @ asm{ xor } @ asm{ mov B, A }
	xor B, A, C                                              => asm{ mov TMP, C } @ asm{ xor } @ asm{ mov B, A }
	xor B, A, X                                              => asm{ mov TMP, X } @ asm{ xor } @ asm{ mov B, A }
	xor B, A, Y                                              => asm{ mov TMP, Y } @ asm{ xor } @ asm{ mov B, A }
	xor B, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ xor } @ asm{ mov B, A }
	xor B, B, TMP                                            => asm{ mov A, B } @ asm{ xor } @ asm{ mov B, A }
	xor B, C, TMP                                            => asm{ mov A, C } @ asm{ xor } @ asm{ mov B, A }
	xor B, X, TMP                                            => asm{ mov A, X } @ asm{ xor } @ asm{ mov B, A }
	xor B, Y, TMP                                            => asm{ mov A, Y } @ asm{ xor } @ asm{ mov B, A }
	xor C, A, A                                              => asm{ mov TMP, A } @ asm{ xor } @ asm{ mov C, A }
	xor C, A, TMP                                            => asm{ xor } @ asm{ mov C, A }
	xor C, A, B                                              => asm{ mov TMP, B } @ asm{ xor } @ asm{ mov C, A }
	xor C, A, C                                              => asm{ mov TMP, C } @ asm{ xor } @ asm{ mov C, A }
	xor C, A, X                                              => asm{ mov TMP, X } @ asm{ xor } @ asm{ mov C, A }
	xor C, A, Y                                              => asm{ mov TMP, Y } @ asm{ xor } @ asm{ mov C, A }
	xor C, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ xor } @ asm{ mov C, A }
	xor C, B, TMP                                            => asm{ mov A, B } @ asm{ xor } @ asm{ mov C, A }
	xor C, C, TMP                                            => asm{ mov A, C } @ asm{ xor } @ asm{ mov C, A }
	xor C, X, TMP                                            => asm{ mov A, X } @ asm{ xor } @ asm{ mov C, A }
	xor C, Y, TMP                                            => asm{ mov A, Y } @ asm{ xor } @ asm{ mov C, A }
	xor X, A, A                                              => asm{ mov TMP, A } @ asm{ xor } @ asm{ mov X, A }
	xor X, A, TMP                                            => asm{ xor } @ asm{ mov X, A }
	xor X, A, B                                              => asm{ mov TMP, B } @ asm{ xor } @ asm{ mov X, A }
	xor X, A, C                                              => asm{ mov TMP, C } @ asm{ xor } @ asm{ mov X, A }
	xor X, A, X                                              => asm{ mov TMP, X } @ asm{ xor } @ asm{ mov X, A }
	xor X, A, Y                                              => asm{ mov TMP, Y } @ asm{ xor } @ asm{ mov X, A }
	xor X, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ xor } @ asm{ mov X, A }
	xor X, B, TMP                                            => asm{ mov A, B } @ asm{ xor } @ asm{ mov X, A }
	xor X, C, TMP                                            => asm{ mov A, C } @ asm{ xor } @ asm{ mov X, A }
	xor X, X, TMP                                            => asm{ mov A, X } @ asm{ xor } @ asm{ mov X, A }
	xor X, Y, TMP                                            => asm{ mov A, Y } @ asm{ xor } @ asm{ mov X, A }
	xor Y, A, A                                              => asm{ mov TMP, A } @ asm{ xor } @ asm{ mov Y, A }
	xor Y, A, TMP                                            => asm{ xor } @ asm{ mov Y, A }
	xor Y, A, B                                              => asm{ mov TMP, B } @ asm{ xor } @ asm{ mov Y, A }
	xor Y, A, C                                              => asm{ mov TMP, C } @ asm{ xor } @ asm{ mov Y, A }
	xor Y, A, X                                              => asm{ mov TMP, X } @ asm{ xor } @ asm{ mov Y, A }
	xor Y, A, Y                                              => asm{ mov TMP, Y } @ asm{ xor } @ asm{ mov Y, A }
	xor Y, TMP, TMP                                          => asm{ mov A, TMP } @ asm{ xor } @ asm{ mov Y, A }
	xor Y, B, TMP                                            => asm{ mov A, B } @ asm{ xor } @ asm{ mov Y, A }
	xor Y, C, TMP                                            => asm{ mov A, C } @ asm{ xor } @ asm{ mov Y, A }
	xor Y, X, TMP                                            => asm{ mov A, X } @ asm{ xor } @ asm{ mov Y, A }
	xor Y, Y, TMP                                            => asm{ mov A, Y } @ asm{ xor } @ asm{ mov Y, A }
	addi {reg1: register}, {reg2: register}, {imm: i8}       => asm{ mov A, {reg2} } @ asm{ addi {imm} } @ asm{ mov {reg1}, A }
	addi A, A, {imm: i8}                                     => asm{ addi {imm} }
	addi A, TMP, {imm: i8}                                   => asm{ mov A, TMP } @ asm{ addi {imm} }
	addi A, B, {imm: i8}                                     => asm{ mov A, B } @ asm{ addi {imm} }
	addi A, C, {imm: i8}                                     => asm{ mov A, C } @ asm{ addi {imm} }
	addi A, X, {imm: i8}                                     => asm{ mov A, X } @ asm{ addi {imm} }
	addi A, Y, {imm: i8}                                     => asm{ mov A, Y } @ asm{ addi {imm} }
	addi TMP, A, {imm: i8}                                   => asm{ addi {imm} } @ asm{ mov TMP, A }
	addi B, A, {imm: i8}                                     => asm{ addi {imm} } @ asm{ mov B, A }
	addi C, A, {imm: i8}                                     => asm{ addi {imm} } @ asm{ mov C, A }
	addi X, A, {imm: i8}                                     => asm{ addi {imm} } @ asm{ mov X, A }
	addi Y, A, {imm: i8}                                     => asm{ addi {imm} } @ asm{ mov Y, A }
	addci {reg1: register}, {reg2: register}, {imm: i8}      => asm{ mov A, {reg2} } @ asm{ addci {imm} } @ asm{ mov {reg1}, A }
	addci A, A, {imm: i8}                                    => asm{ addci {imm} }
	addci A, TMP, {imm: i8}                                  => asm{ mov A, TMP } @ asm{ addci {imm} }
	addci A, B, {imm: i8}                                    => asm{ mov A, B } @ asm{ addci {imm} }
	addci A, C, {imm: i8}                                    => asm{ mov A, C } @ asm{ addci {imm} }
	addci A, X, {imm: i8}                                    => asm{ mov A, X } @ asm{ addci {imm} }
	addci A, Y, {imm: i8}                                    => asm{ mov A, Y } @ asm{ addci {imm} }
	addci TMP, A, {imm: i8}                                  => asm{ addci {imm} } @ asm{ mov TMP, A }
	addci B, A, {imm: i8}                                    => asm{ addci {imm} } @ asm{ mov B, A }
	addci C, A, {imm: i8}                                    => asm{ addci {imm} } @ asm{ mov C, A }
	addci X, A, {imm: i8}                                    => asm{ addci {imm} } @ asm{ mov X, A }
	addci Y, A, {imm: i8}                                    => asm{ addci {imm} } @ asm{ mov Y, A }
	subci {reg1: register}, {reg2: register}, {imm: i8}      => asm{ mov A, {reg2} } @ asm{ subci {imm} } @ asm{ mov {reg1}, A }
	subci A, A, {imm: i8}                                    => asm{ subci {imm} }
	subci A, TMP, {imm: i8}                                  => asm{ mov A, TMP } @ asm{ subci {imm} }
	subci A, B, {imm: i8}                                    => asm{ mov A, B } @ asm{ subci {imm} }
	subci A, C, {imm: i8}                                    => asm{ mov A, C } @ asm{ subci {imm} }
	subci A, X, {imm: i8}                                    => asm{ mov A, X } @ asm{ subci {imm} }
	subci A, Y, {imm: i8}                                    => asm{ mov A, Y } @ asm{ subci {imm} }
	subci TMP, A, {imm: i8}                                  => asm{ subci {imm} } @ asm{ mov TMP, A }
	subci B, A, {imm: i8}                                    => asm{ subci {imm} } @ asm{ mov B, A }
	subci C, A, {imm: i8}                                    => asm{ subci {imm} } @ asm{ mov C, A }
	subci X, A, {imm: i8}                                    => asm{ subci {imm} } @ asm{ mov X, A }
	subci Y, A, {imm: i8}                                    => asm{ subci {imm} } @ asm{ mov Y, A }
	andi {reg1: register}, {reg2: register}, {imm: i8}       => asm{ mov A, {reg2} } @ asm{ andi {imm} } @ asm{ mov {reg1}, A }
	andi A, A, {imm: i8}                                     => asm{ andi {imm} }
	andi A, TMP, {imm: i8}                                   => asm{ mov A, TMP } @ asm{ andi {imm} }
	andi A, B, {imm: i8}                                     => asm{ mov A, B } @ asm{ andi {imm} }
	andi A, C, {imm: i8}                                     => asm{ mov A, C } @ asm{ andi {imm} }
	andi A, X, {imm: i8}                                     => asm{ mov A, X } @ asm{ andi {imm} }
	andi A, Y, {imm: i8}                                     => asm{ mov A, Y } @ asm{ andi {imm} }
	andi TMP, A, {imm: i8}                                   => asm{ andi {imm} } @ asm{ mov TMP, A }
	andi B, A, {imm: i8}                                     => asm{ andi {imm} } @ asm{ mov B, A }
	andi C, A, {imm: i8}                                     => asm{ andi {imm} } @ asm{ mov C, A }
	andi X, A, {imm: i8}                                     => asm{ andi {imm} } @ asm{ mov X, A }
	andi Y, A, {imm: i8}                                     => asm{ andi {imm} } @ asm{ mov Y, A }
	ori {reg1: register}, {reg2: register}, {imm: i8}        => asm{ mov A, {reg2} } @ asm{ ori {imm} } @ asm{ mov {reg1}, A }
	ori A, A, {imm: i8}                                      => asm{ ori {imm} }
	ori A, TMP, {imm: i8}                                    => asm{ mov A, TMP } @ asm{ ori {imm} }
	ori A, B, {imm: i8}                                      => asm{ mov A, B } @ asm{ ori {imm} }
	ori A, C, {imm: i8}                                      => asm{ mov A, C } @ asm{ ori {imm} }
	ori A, X, {imm: i8}                                      => asm{ mov A, X } @ asm{ ori {imm} }
	ori A, Y, {imm: i8}                                      => asm{ mov A, Y } @ asm{ ori {imm} }
	ori TMP, A, {imm: i8}                                    => asm{ ori {imm} } @ asm{ mov TMP, A }
	ori B, A, {imm: i8}                                      => asm{ ori {imm} } @ asm{ mov B, A }
	ori C, A, {imm: i8}                                      => asm{ ori {imm} } @ asm{ mov C, A }
	ori X, A, {imm: i8}                                      => asm{ ori {imm} } @ asm{ mov X, A }
	ori Y, A, {imm: i8}                                      => asm{ ori {imm} } @ asm{ mov Y, A }
	xori {reg1: register}, {reg2: register}, {imm: i8}       => asm{ mov A, {reg2} } @ asm{ xori {imm} } @ asm{ mov {reg1}, A }
	xori A, A, {imm: i8}                                     => asm{ xori {imm} }
	xori A, TMP, {imm: i8}                                   => asm{ mov A, TMP } @ asm{ xori {imm} }
	xori A, B, {imm: i8}                                     => asm{ mov A, B } @ asm{ xori {imm} }
	xori A, C, {imm: i8}                                     => asm{ mov A, C } @ asm{ xori {imm} }
	xori A, X, {imm: i8}                                     => asm{ mov A, X } @ asm{ xori {imm} }
	xori A, Y, {imm: i8}                                     => asm{ mov A, Y } @ asm{ xori {imm} }
	xori TMP, A, {imm: i8}                                   => asm{ xori {imm} } @ asm{ mov TMP, A }
	xori B, A, {imm: i8}                                     => asm{ xori {imm} } @ asm{ mov B, A }
	xori C, A, {imm: i8}                                     => asm{ xori {imm} } @ asm{ mov C, A }
	xori X, A, {imm: i8}                                     => asm{ xori {imm} } @ asm{ mov X, A }
	xori Y, A, {imm: i8}                                     => asm{ xori {imm} } @ asm{ mov Y, A }
	not {reg1: register}, {reg2: register}                   => asm{ mov A, {reg2} } @ asm{ not } @ asm{ mov {reg1}, A }
	not A, A                                                 => asm{ not }
	not A, TMP                                               => asm{ mov A, TMP } @ asm{ not }
	not A, B                                                 => asm{ mov A, B } @ asm{ not }
	not A, C                                                 => asm{ mov A, C } @ asm{ not }
	not A, X                                                 => asm{ mov A, X } @ asm{ not }
	not A, Y                                                 => asm{ mov A, Y } @ asm{ not }
	not TMP, A                                               => asm{ not } @ asm{ mov TMP, A }
	not B, A                                                 => asm{ not } @ asm{ mov B, A }
	not C, A                                                 => asm{ not } @ asm{ mov C, A }
	not X, A                                                 => asm{ not } @ asm{ mov X, A }
	not Y, A                                                 => asm{ not } @ asm{ mov Y, A }
	negate {reg1: register}, {reg2: register}                => asm{ mov A, {reg2} } @ asm{ negate } @ asm{ mov {reg1}, A }
	negate A, A                                              => asm{ negate }
	negate A, TMP                                            => asm{ mov A, TMP } @ asm{ negate }
	negate A, B                                              => asm{ mov A, B } @ asm{ negate }
	negate A, C                                              => asm{ mov A, C } @ asm{ negate }
	negate A, X                                              => asm{ mov A, X } @ asm{ negate }
	negate A, Y                                              => asm{ mov A, Y } @ asm{ negate }
	negate TMP, A                                            => asm{ negate } @ asm{ mov TMP, A }
	negate B, A                                              => asm{ negate } @ asm{ mov B, A }
	negate C, A                                              => asm{ negate } @ asm{ mov C, A }
	negate X, A                                              => asm{ negate } @ asm{ mov X, A }
	negate Y, A                                              => asm{ negate } @ asm{ mov Y, A }
	shl {reg1: register}, {reg2: register}                   => asm{ mov A, {reg2} } @ asm{ shl } @ asm{ mov {reg1}, A }
	shl A, A                                                 => asm{ shl }
	shl A, TMP                                               => asm{ mov A, TMP } @ asm{ shl }
	shl A, B                                                 => asm{ mov A, B } @ asm{ shl }
	shl A, C                                                 => asm{ mov A, C } @ asm{ shl }
	shl A, X                                                 => asm{ mov A, X } @ asm{ shl }
	shl A, Y                                                 => asm{ mov A, Y } @ asm{ shl }
	shl TMP, A                                               => asm{ shl } @ asm{ mov TMP, A }
	shl B, A                                                 => asm{ shl } @ asm{ mov B, A }
	shl C, A                                                 => asm{ shl } @ asm{ mov C, A }
	shl X, A                                                 => asm{ shl } @ asm{ mov X, A }
	shl Y, A                                                 => asm{ shl } @ asm{ mov Y, A }
	slr {reg1: register}, {reg2: register}                   => asm{ mov A, {reg2} } @ asm{ slr } @ asm{ mov {reg1}, A }
	slr A, A                                                 => asm{ slr }
	slr A, TMP                                               => asm{ mov A, TMP } @ asm{ slr }
	slr A, B                                                 => asm{ mov A, B } @ asm{ slr }
	slr A, C                                                 => asm{ mov A, C } @ asm{ slr }
	slr A, X                                                 => asm{ mov A, X } @ asm{ slr }
	slr A, Y                                                 => asm{ mov A, Y } @ asm{ slr }
	slr TMP, A                                               => asm{ slr } @ asm{ mov TMP, A }
	slr B, A                                                 => asm{ slr } @ asm{ mov B, A }
	slr C, A                                                 => asm{ slr } @ asm{ mov C, A }
	slr X, A                                                 => asm{ slr } @ asm{ mov X, A }
	slr Y, A                                                 => asm{ slr } @ asm{ mov Y, A }
	sar {reg1: register}, {reg2: register}                   => asm{ mov A, {reg2} } @ asm{ sar } @ asm{ mov {reg1}, A }
	sar A, A                                                 => asm{ sar }
	sar A, TMP                                               => asm{ mov A, TMP } @ asm{ sar }
	sar A, B                                                 => asm{ mov A, B } @ asm{ sar }
	sar A, C                                                 => asm{ mov A, C } @ asm{ sar }
	sar A, X                                                 => asm{ mov A, X } @ asm{ sar }
	sar A, Y                                                 => asm{ mov A, Y } @ asm{ sar }
	sar TMP, A                                               => asm{ sar } @ asm{ mov TMP, A }
	sar B, A                                                 => asm{ sar } @ asm{ mov B, A }
	sar C, A                                                 => asm{ sar } @ asm{ mov C, A }
	sar X, A                                                 => asm{ sar } @ asm{ mov X, A }
	sar Y, A                                                 => asm{ sar } @ asm{ mov Y, A }
	ror {reg1: register}, {reg2: register}                   => asm{ mov A, {reg2} } @ asm{ ror } @ asm{ mov {reg1}, A }
	ror A, A                                                 => asm{ ror }
	ror A, TMP                                               => asm{ mov A, TMP } @ asm{ ror }
	ror A, B                                                 => asm{ mov A, B } @ asm{ ror }
	ror A, C                                                 => asm{ mov A, C } @ asm{ ror }
	ror A, X                                                 => asm{ mov A, X } @ asm{ ror }
	ror A, Y                                                 => asm{ mov A, Y } @ asm{ ror }
	ror TMP, A                                               => asm{ ror } @ asm{ mov TMP, A }
	ror B, A                                                 => asm{ ror } @ asm{ mov B, A }
	ror C, A                                                 => asm{ ror } @ asm{ mov C, A }
	ror X, A                                                 => asm{ ror } @ asm{ mov X, A }
	ror Y, A                                                 => asm{ ror } @ asm{ mov Y, A }
	rol {reg1: register}, {reg2: register}                   => asm{ mov A, {reg2} } @ asm{ rol } @ asm{ mov {reg1}, A }
	rol A, A                                                 => asm{ rol }
	rol A, TMP                                               => asm{ mov A, TMP } @ asm{ rol }
	rol A, B                                                 => asm{ mov A, B } @ asm{ rol }
	rol A, C                                                 => asm{ mov A, C } @ asm{ rol }
	rol A, X                                                 => asm{ mov A, X } @ asm{ rol }
	rol A, Y                                                 => asm{ mov A, Y } @ asm{ rol }
	rol TMP, A                                               => asm{ rol } @ asm{ mov TMP, A }
	rol B, A                                                 => asm{ rol } @ asm{ mov B, A }
	rol C, A                                                 => asm{ rol } @ asm{ mov C, A }
	rol X, A                                                 => asm{ rol } @ asm{ mov X, A }
	rol Y, A                                                 => asm{ rol } @ asm{ mov Y, A }
}

#bank ROM
